
from interlap import InterLap

from cerberus.interval import Interval
from cerberus.samplers import ListSampler, MultiSampler, RandomSampler, ScaledSampler


def test_multisampler_seed_propagation():
    """
    Verify that MultiSampler distributes unique seeds to its sub-samplers
    to avoid correlated randomness when sub-samplers are identical.
    """
    # Create a base sampler with 100 intervals
    intervals = [Interval("chr1", i, i+100, "+") for i in range(100)]
    base_sampler = ListSampler(intervals=intervals)
    
    # Create two ScaledSamplers wrapping the same base.
    s1 = ScaledSampler(base_sampler, num_samples=10, seed=1)
    s2 = ScaledSampler(base_sampler, num_samples=10, seed=2)
    
    # Wrap in MultiSampler with a seed
    ms = MultiSampler([s1, s2], chrom_sizes={}, exclude_intervals={}, seed=123)
    
    # Check that they produced different samples (due to seed+i logic)
    # With seed=123:
    # s1 gets seed 123
    # s2 gets seed 124
    assert s1._indices != s2._indices, "Sub-samplers should have different indices initially"
    
    # Resample
    ms.resample(seed=999)
    
    # s1 gets seed 999
    # s2 gets seed 1000
    assert s1._indices != s2._indices, "Sub-samplers should have different indices after resample"

def test_scaled_sampler_determinism():
    """
    Verify ScaledSampler determinism and sticky seed behavior.
    """
    intervals = [Interval("chr1", i, i+100, "+") for i in range(100)]
    base_sampler = ListSampler(intervals=intervals)
    
    # 1. Init with seed
    s = ScaledSampler(base_sampler, num_samples=10, seed=42)
    indices_1 = s._indices.copy()
    
    # 2. Resample with None (should advance RNG)
    s.resample(None)
    indices_2 = s._indices.copy()
    assert indices_1 != indices_2, "Resample(None) should advance RNG and produce new indices"
    
    # 3. Resample with new seed
    s.resample(43)
    indices_3 = s._indices.copy()
    assert indices_1 != indices_3, "Resample(new_seed) should change indices"
    
    # 4. Resample with None again (should advance RNG)
    s.resample(None)
    indices_4 = s._indices.copy()
    assert indices_3 != indices_4, "Resample(None) should advance RNG and produce new indices"
    
def test_scaled_sampler_split_folds_determinism():
    """
    Verify that split_folds is deterministic based on the seed.
    """
    intervals = [Interval("chr1", i, i+100, "+") for i in range(100)]
    base_sampler = ListSampler(intervals=intervals, folds=[])
    
    s = ScaledSampler(base_sampler, num_samples=10, seed=42)
    
    # Split 1
    train1, val1, test1 = s.split_folds()
    
    # Split 2 (should be identical)
    train2, val2, test2 = s.split_folds()
    
    # ScaledSampler.split_folds returns new ScaledSamplers with randomized seeds.
    # The split logic itself for ListSampler is deterministic (based on folds).
    # But ScaledSampler also determines the size and seed of the new samplers.
    # The seeds of the child samplers are generated by `rng.randint`.
    
    assert train1.seed == train2.seed
    assert val1.seed == val2.seed
    assert test1.seed == test2.seed
    
    # If we change the seed of the parent, children seeds should change
    s.resample(43)
    train3, val3, test3 = s.split_folds()
    assert train1.seed != train3.seed

    # 5. Split with None seed
    s.resample(None) # Resets to sticky seed 43 if previous test passed, or whatever logic.
    # Wait, my logic for resample(None) is: if None, use self.seed.
    # self.seed was 43. So it uses 43.
    
    # Verify split_folds produces deterministic derived seeds
    s2 = ScaledSampler(base_sampler, num_samples=10, seed=99)
    t1, v1, te1 = s2.split_folds()
    assert isinstance(t1.seed, int)
    assert isinstance(v1.seed, int)
    assert isinstance(te1.seed, int)

def test_random_sampler_split_folds_idempotency():
    """
    Test if RandomSampler.split_folds returns the same seeds/samplers
    when called multiple times on the same seeded object.
    """
    chrom_sizes = {"chr1": 10000}
    padded_size = 100
    num_intervals = 10
    seed = 42
    folds = [
        {"chr1": InterLap([(0, 5000)])},
        {"chr1": InterLap([(5000, 10000)])}
    ]
    
    rs = RandomSampler(
        chrom_sizes=chrom_sizes,
        padded_size=padded_size,
        num_intervals=num_intervals,
        folds=folds,
        seed=seed
    )
    
    # First split
    t1, v1, te1 = rs.split_folds(test_fold=0, val_fold=1)
    
    # Second split
    t2, v2, te2 = rs.split_folds(test_fold=0, val_fold=1)
    
    # Check seeds
    assert t1.seed == t2.seed, "RandomSampler split seeds should be idempotent given a fixed parent seed"
    assert v1.seed == v2.seed
    assert te1.seed == te2.seed

def test_multisampler_split_folds_seed_propagation_consistency():
    """
    Test if MultiSampler propagates its seed to split instances
    and if splitting is idempotent.
    """
    chrom_sizes = {"chr1": 10000}
    padded_size = 100
    num_intervals = 10
    seed = 42
    folds = [
        {"chr1": InterLap([(0, 5000)])},
        {"chr1": InterLap([(5000, 10000)])}
    ]
    
    rs = RandomSampler(chrom_sizes, padded_size, num_intervals, folds=folds, seed=seed)
    ms = MultiSampler([rs], chrom_sizes, folds=folds, exclude_intervals={}, seed=seed)
    
    # Split 1
    t1, v1, te1 = ms.split_folds(test_fold=0, val_fold=1)
    
    # Split 2
    t2, v2, te2 = ms.split_folds(test_fold=0, val_fold=1)
    
    # Check if splits have seeds
    assert t1.seed is not None, "MultiSampler split should have a seed derived from parent"
    assert v1.seed is not None
    assert te1.seed is not None
    
    # Check idempotency
    assert t1.seed == t2.seed, "MultiSampler split seeds should be idempotent"
    assert v1.seed == v2.seed
    assert te1.seed == te2.seed

def test_multisampler_resample_updates_seed():
    """
    Test if MultiSampler.resample(None) updates its seed,
    leading to different splits for the next epoch.
    """
    chrom_sizes = {"chr1": 10000}
    padded_size = 100
    num_intervals = 10
    seed = 42
    folds = [
        {"chr1": InterLap([(0, 5000)])},
        {"chr1": InterLap([(5000, 10000)])}
    ]
    
    rs = RandomSampler(chrom_sizes, padded_size, num_intervals, folds=folds, seed=seed)
    ms = MultiSampler([rs], chrom_sizes, folds=folds, exclude_intervals={}, seed=seed)
    
    # Split 1 (Epoch 0)
    t1, _, _ = ms.split_folds(test_fold=0, val_fold=1)
    seed1 = t1.seed
    
    # Resample (Epoch 1)
    ms.resample(None)
    
    # Split 2 (Epoch 1)
    t2, _, _ = ms.split_folds(test_fold=0, val_fold=1)
    seed2 = t2.seed
    
    assert seed1 != seed2, "MultiSampler split seeds should change after resample(None)"
