
import random
import pytest
from cerberus.samplers import ScaledSampler, MultiSampler, ListSampler
from cerberus.interval import Interval

def test_multisampler_seed_propagation():
    """
    Verify that MultiSampler distributes unique seeds to its sub-samplers
    to avoid correlated randomness when sub-samplers are identical.
    """
    # Create a base sampler with 100 intervals
    intervals = [Interval("chr1", i, i+100, "+") for i in range(100)]
    base_sampler = ListSampler(intervals=intervals)
    
    # Create two ScaledSamplers wrapping the same base.
    s1 = ScaledSampler(base_sampler, num_samples=10, seed=1)
    s2 = ScaledSampler(base_sampler, num_samples=10, seed=2)
    
    # Wrap in MultiSampler with a seed
    ms = MultiSampler([s1, s2], chrom_sizes={}, exclude_intervals={}, seed=123)
    
    # Check that they produced different samples (due to seed+i logic)
    # With seed=123:
    # s1 gets seed 123
    # s2 gets seed 124
    assert s1._indices != s2._indices, "Sub-samplers should have different indices initially"
    
    # Resample
    ms.resample(seed=999)
    
    # s1 gets seed 999
    # s2 gets seed 1000
    assert s1._indices != s2._indices, "Sub-samplers should have different indices after resample"

def test_scaled_sampler_determinism():
    """
    Verify ScaledSampler determinism and sticky seed behavior.
    """
    intervals = [Interval("chr1", i, i+100, "+") for i in range(100)]
    base_sampler = ListSampler(intervals=intervals)
    
    # 1. Init with seed
    s = ScaledSampler(base_sampler, num_samples=10, seed=42)
    indices_1 = s._indices.copy()
    
    # 2. Resample with None (should use sticky seed 42)
    s.resample(None)
    indices_2 = s._indices.copy()
    assert indices_1 == indices_2, "Resample(None) should respect sticky seed"
    
    # 3. Resample with new seed
    s.resample(43)
    indices_3 = s._indices.copy()
    assert indices_1 != indices_3, "Resample(new_seed) should change indices"
    
    # 4. Resample with None again (should use sticky seed 43)
    s.resample(None)
    indices_4 = s._indices.copy()
    assert indices_3 == indices_4, "Resample(None) should respect updated sticky seed"
    
def test_scaled_sampler_split_folds_determinism():
    """
    Verify that split_folds is deterministic based on the seed.
    """
    intervals = [Interval("chr1", i, i+100, "+") for i in range(100)]
    base_sampler = ListSampler(intervals=intervals, folds=[])
    
    s = ScaledSampler(base_sampler, num_samples=10, seed=42)
    
    # Split 1
    train1, val1, test1 = s.split_folds()
    
    # Split 2 (should be identical)
    train2, val2, test2 = s.split_folds()
    
    # ScaledSampler.split_folds returns new ScaledSamplers with randomized seeds.
    # The split logic itself for ListSampler is deterministic (based on folds).
    # But ScaledSampler also determines the size and seed of the new samplers.
    # The seeds of the child samplers are generated by `rng.randint`.
    
    assert train1.seed == train2.seed
    assert val1.seed == val2.seed
    assert test1.seed == test2.seed
    
    # If we change the seed of the parent, children seeds should change
    s.resample(43)
    train3, val3, test3 = s.split_folds()
    assert train1.seed != train3.seed

    # 5. Split with None seed
    s.resample(None) # Resets to sticky seed 43 if previous test passed, or whatever logic.
    # Wait, my logic for resample(None) is: if None, use self.seed.
    # self.seed was 43. So it uses 43.
    
    # Let's force None by creating new sampler
    s_none = ScaledSampler(base_sampler, num_samples=10, seed=None)
    t1, v1, te1 = s_none.split_folds()
    assert t1.seed is None
    assert v1.seed is None
    assert te1.seed is None
